### PR TITLE
Allow Symfony 2.7

### PR DESCRIPTION
**Pull request by mathielen**
The bundle also works with symfony 2.7

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Hi and thanks for this PR.

I don't know if we want to have 2.7 support because this bundle will evolve and we don't want to manage BC for this new project before SF 2.8.

**Comment by mathielen** [comment]
Thanks for the quick answer. I have project that still uses 2.7.

Since symfony 2.7 has LTS until 2018 you might consider supporting it: http://symfony.com/doc/current/contributing/community/releases.html#schedule

**Comment by Soullivaneuh** [comment]
> Since symfony 2.7 has LTS until 2018 you might consider supporting it:

Yeah and 2.3 is security supported until 2017. IMO, this is not an obligation to support older versions for new projects.

But, I will accept for 2.7 for now. If we have BC break changes later, we'll push a new major version.

Could you please:

* Resolve conflict?
* Add SF 2.7 version on `.travis.yml`?

Thanks.

**Comment by Soullivaneuh** [comment]
Also can you please update [`README.md`](https://github.com/nexylan/NexySlackBundle#documentation) file?

**Comment by Soullivaneuh** [comment]
One last thing once finished: Please squash your commits and rename the comment for a proper title : "Allow Symfony 2.7".

**Comment by Soullivaneuh** [comment]
ping @mathielen. Could please rebase so I can push a new release?

Thanks! :+1:

**Comment by Soullivaneuh** [comment]
ping @mathielen ? :-)

**Comment by Soullivaneuh** [comment]
Closed in favor of #9.

**Pull request closed without merging**
