### PR TITLE
feat: php 8 support

### PR DESCRIPTION
**Pull request by ndench**
Just copied the https://github.com/nexylan/slack/pull/70 pull request.

### CODE REVIEW

**Comment by ndench** [comment]
Symfony changed it configuration exception messages when updating to 5.0, so I had to modify a test. I dropped PHP 7.3 support because nexylan/slack#70 did the same.

The `--prefer-lowest` build is failing because it's installing PHPUnit 8.0 which seems to not be working with xdebug 3. I'm not sure how to fix this.

**Comment by soullivaneuh** [comment]
@ndench Thanks! Can you allow me edition on this PR so I can take a look and finish it?

**Comment by ndench** [comment]
No problem @soullivaneuh. I've invited you to my fork as a maintainer, feel free to make any changes necessary. I'm happy to help with anything you need as well.

**Comment by soullivaneuh** [comment]
@ndench Thanks, but by allowing edition, I meant this: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

;-)

**Comment by ndench** [comment]
Unfortunately allowing edits from maintainers appears to only work if the fork is created from a user account. However I created this fork from an organisation account so that checkbox is not available for me. See https://github.community/t/how-can-we-enable-allow-edits-from-maintainers-by-default/2847/6

I do not see the checkbox shown in the docs link:
image

Feel free to edit as a maintainer, or even create a separate branch and pull in my commits if you like.
I could also re-fork the repository if that's easier too?

**Comment by ndench** [comment]
@soullivaneuh I got the test passing. The `--prefer-lowest` option was installing a version of `php-code-coverage` which wasn't reading the xdebug mode properly. See [this issue](https://github.com/sebastianbergmann/php-code-coverage/issues/834). It was also installing PHPUnit 8.0 which doesn't have the new `expectExceptionMessageMatches` function which was introduced it 8.4.

We can solve these by:
- Specifying `XDEBUG_MODE=coverage` as mentioned in the linked issue above
- Requiring PHPUnit minimum 8.4

**Comment by soullivaneuh** [comment]
Hello,

Thanks for giving some time on it! :+1: 

Looks goot to me.

**Pull request merged**
